//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElasticSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int id { get; set; }
        public string ssn { get; set; }
        public string gender { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string dob { get; set; }
        public string cell { get; set; }
        public Nullable<double> salary { get; set; }
        public string interests { get; set; }
        public string json_data { get; set; }
        public string Description { get; set; }
        public string zip { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
    }
}
